language: rust
rust:
  - 1.39.0

before_install:
  - rustup component add rustfmt
  
before_script:
  - echo $TRAVIS_COMMIT
  - echo $TRAVIS_TAG
  - echo $TRAVIS_BRANCH
  - echo $TRAVIS_BUILD_NUMBER
  - echo $TRAVIS_REPO_SLUG

script:
  # Lint, build common
  - cargo fmt -- --check
  - cargo build
